### ISSUE TITLE
Can't find spidev* under /dev/

### ISSUE THREAD

**Issue by lindo0130** [jumpnow/meta-bbb#7]
Hi, I followed the tutorial in your website and build qt5-image using the dtb **bbb-4dcape70.dtb**.

I got `open: No such file or directory` error message when I was running **spiloop** test app. And then I found there are no spidev* device under `/dev/`

Did I miss something or should I did some configuration before I use it? Thank you!

**Comment by scottellis** [comment]
See this note in the bbb-4dcape70t.dts

/* The 4dcape DOWN button gpio3[16] conflicts with SPI1.d0
   You can choose either the keypad.dtsi or the spi1-spidev dtsi,
   but not both unless you comment out the 'DOWN' key defs in
   bbb-4dcape70t-keypad.dtsi.
*/
#include "bbb-4dcape70t-keypad.dtsi"


So it's possible to use the 4dcape and spidev with spi1, but you'll
have to make some decisions.

**Comment by lindo0130** [comment]
OK, I'll try to comment the 'DOWN' key define.

And sorry for another stupid question, I have tried a normal HDMI touchscreen which using the `ft5x06` driver with the dtb **bbb-hdmi.dtb**. The screen show nothing, while the normal screen without touch work as expected. Could you give me some advice? (I have modified touchscreen_dtb, add a use_touchscreen file to the `/boot` and also add `ft5x06_ts` driver to `/etc/modules`)

Really appreciate your reply, Thanks!

**Comment by scottellis** [comment]
Could you send me your dts?

Email me direct at scott@jumpnowtek.com

"lindo0130" <notifications@github.com> said:
